Repository International-Data-Spaces-Association/IDS-ConfigurationManager, pull requests merged in 2021-07, with the labels that each got.

#198 docs: update readme for camel
  README.md
Labels: Type: Documentation, Version 7

#199 feat: adapt changes from v7 (feat: maven plugin for Apache 2.0 license header)
  CHANGELOG.md
  Dockerfile
  docker-compose.yml
  pom.xml
  scripts/ci/license/header.txt
  src/main/java/de/fraunhofer/isst/configmanager/extensions/routes/camel/exceptions/package-info.java
  src/main/java/de/fraunhofer/isst/configmanager/extensions/routes/camel/package-info.java
Labels: Version 8

#194 chore: add scripts for docker image building
  .dockerignore
  .github/workflows/maven-build.yml
  .hadolint.yaml
Labels: Status: Under Review, Type: Enhancement, Version 7

#192 Extension: Component AppStore
  src/main/java/de/fraunhofer/isst/configmanager/extensions/components/appstore/api/AppStoreApi.java
  src/main/java/de/fraunhofer/isst/configmanager/extensions/components/appstore/api/controller/AppStoreController.java
  src/main/java/de/fraunhofer/isst/configmanager/extensions/components/appstore/api/service/AppStoreService.java
Labels: Status: In Progress, Type: Feature, Version 8
