Repository International-Data-Spaces-Association/IDS-ConfigurationManager, pull requests merged in 2021-04, with the labels that each got.

#101 83 update resources
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/BrokerController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceController.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/clients/DefaultBrokerClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/clients/DefaultResourceClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/clients/DataspaceBrokerClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/clients/DataspaceResourceClient.java
Labels: Status: Under Review

#113 refactor: clean up unused APIs (not used by UI)
  src/main/java/de/fraunhofer/isst/configmanager/api/AppApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/AppRouteApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/BrokerApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ConfigModelApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ConnectorApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/EndpointApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ResourceApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ResourceContractApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ResourceRepresentationApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/AppController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/AppRouteController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/BrokerController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ConfigModelController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ConnectorController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ConnectorRequestController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/EndpointController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceContractController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceRepresentationController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/AppRouteService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/AppService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/BrokerService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ConnectorService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ResourceService.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/clients/DefaultResourceClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/clients/DataspaceConnectorClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/clients/DataspaceResourceClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/util/ResourceMapper.java
  src/test/java/de/fraunhofer/isst/configmanager/api_test/BrokerUIAPITest.java
Labels: Type: Maintenance

#111 Refactor ResourceService
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/AppRouteController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceContractController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceRepresentationController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/AppRouteService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/BrokerService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ResourceService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/resources/AbstractResourceService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/resources/ResourceContractBuilder.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/resources/ResourceContractService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/resources/ResourceRepresentationService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/resources/ResourceService.java
  src/test/java/de/fraunhofer/isst/configmanager/api_test/BrokerUIAPITest.java
Labels: Status: Under Review, Type: Maintenance

#109 refactor: using labels instead of enum names for better ux
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/configmanager/api/service/UtilService.java
Labels: Status: Under Review, Type: Enhancement

#116 chore: disabled Swagger-Petstore default playground
  CHANGELOG.md
  pom.xml
  src/main/resources/application.properties
Labels: Status: In Progress

#108 Fix for Issue #80
  src/main/java/de/fraunhofer/isst/configmanager/api/ConfigModelApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ConnectorApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/EndpointApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ResourceApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ConfigModelController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ConnectorController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/EndpointController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ResourceController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ConfigModelService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ConnectorService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/EndpointService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/resources/ResourceService.java
Labels: Status: Under Review, Type: Bug

#114 Retrieve IDS Resources
  src/main/java/de/fraunhofer/isst/configmanager/api/AppRouteApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/BrokerApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ConnectorRequestApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/EndpointApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/ResourceApi.java
  src/main/java/de/fraunhofer/isst/configmanager/api/controller/ConnectorRequestController.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ConfigModelService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/ConnectorRequestService.java
  src/main/java/de/fraunhofer/isst/configmanager/api/service/EndpointService.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/clients/DefaultConnectorClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/clients/DefaultResourceClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/clients/DataspaceConnectorClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/clients/DataspaceResourceClient.java
  src/main/java/de/fraunhofer/isst/configmanager/connector/dataspaceconnector/util/ResourceMapper.java
  src/main/java/de/fraunhofer/isst/configmanager/model/config/ConfigModelObject.java
  src/main/java/de/fraunhofer/isst/configmanager/model/config/CustomBroker.java
  src/main/java/de/fraunhofer/isst/configmanager/model/config/QueryInput.java
  src/main/java/de/fraunhofer/isst/configmanager/model/configlists/CustomGenericEndpointList.java
  src/main/java/de/fraunhofer/isst/configmanager/model/customapp/CustomApp.java
  src/main/java/de/fraunhofer/isst/configmanager/model/customgenericendpoint/BackendConfig.java
  src/main/java/de/fraunhofer/isst/configmanager/util/Utility.java
Labels: Status: Under Review
